using Microsoft.AspNetCore.Mvc;

namespace ExampleApi.Models
{
    /// <summary>
    /// Represents any type of error generated by the API.
    /// Actual exceptions may differ.
    /// </summary>
    public class ApiError
    {
        /// <summary>Key for any related error glossary/dictionary.</summary>
        public string Code { get; private set; }

        /// <summary>Informative summary of the problem.</summary>
        public string Details { get; private set; }

        /// <summary>Create a BadRequest response.</summary>
        public static ActionResult BadRequest(string code, string details)
        {
            return new BadRequestObjectResult(new ApiError(code, details));
        }

        /// <summary>Create a NotFound response.</summary>
        public static ActionResult NotFound(string code, string details)
        {
            return new NotFoundObjectResult(new ApiError(code, details));
        }

        /// <summary>Create a populated API error model.</summary>
        /// <remarks>Private as should be using specific methods (eg BadRequest).</remarks>
        private ApiError(string code, string details)
        {
            Code = code;
            Details = details;
        }
    }
}
